services:

  mysql:
    image: mysql:8.4
    container_name: shared_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shared_network

  redis:
    image: redis:7-alpine
    container_name: shared_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shared_network

  mailpit:
    image: axllent/mailpit
    container_name: shared_mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - shared_network

  minio:
    image: minio/minio
    container_name: shared_minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio_data:/data
    networks:
      - shared_network

volumes:
  mysql_data:
  redis_data:
  minio_data:

networks:
  shared_network:
    name: shared_network
